// Generated by CoffeeScript 1.7.1
(function() {
  $(function() {
    var clearBoard, isX;
    isX = true;
    clearBoard = function() {
      $('.board-cell').text('');
      return isX = true;
    };
    $('#start-game').on('click', function(e) {
      clearboard();
      $(this).hide();
      return $('#gameboard').fadeIn(500);
    });
    return $('.board-cell').on('click', function(e) {
      var isx, mark;
      mark = isX ? 'x' : 'o';
      if (($(this).text().replace(/^\s+|\s+$/g, "")) === '') {
        $(this).text(mark);
        $(this).addClass(mark);
        return isx = !isX;
      }
    });
  });

}).call(this);

//# sourceMappingURL=game.map
